### ISSUE TITLE
& vs &&

### ISSUE THREAD

**Issue by 0xWOF** [MineScroll/Cubby#1]
<img width="447" alt="2016-08-07 9 00 54" src="https://cloud.githubusercontent.com/assets/7144012/17462301/a3987c10-5ce3-11e6-974d-8efd087c73ad.png">
이 소스에 대해서 && 보다 &를 사용하는걸 추천합니다.

이 테스트 코드로 테스트시
<img width="651" alt="2016-08-07 9 28 11" src="https://cloud.githubusercontent.com/assets/7144012/17462381/e2ba3ba2-5ce5-11e6-9543-6963a5c53913.png">

이유는 컴파일 시 어셈블리가
<img width="256" alt="2016-08-07 9 07 28" src="https://cloud.githubusercontent.com/assets/7144012/17462304/b8192586-5ce3-11e6-95c8-35dc1eb114f4.png">
이렇게 나타나는데 분기명령은 명령어 종속성이 명확하기 때문에 슈퍼스칼라 대상이 아닙니다.
그래서
true : <비교> -> <분기점프> -> <분기> 
false : <비교> -> <분기점프> (앞의 state 가 false 면 &&는 false 로 하는 것)

하지만 & 연산을 사용하면 두 비교사이에 명령어 종속성이 존재하지 않아 "아마" 슈퍼스칼라 대상이 되서 
<비교>, <비교> (슈퍼스칼라에 의해 동시수행) -> <"AND"> 
연산으로 이루어 질 것입니다.

(슈퍼스칼라 : cpu 가 자동으로 명령어배열을 명령어 종속성을 검사해서 비순차적 및 병렬적으로 수행하는 기술)

그래서 3클록 or 2클록 을 2클록으로 줄일 수 있다고 생각합니다.

GCC 5.3.0 Clang 에서 테스트한 결과는 다음과 같습니다. (나노초 기준)
<img width="682" alt="2016-08-07 8 59 19" src="https://cloud.githubusercontent.com/assets/7144012/17462341/b67eff4c-5ce4-11e6-8228-791ad62ec26c.png">
분기예측은 명령어를 수행한 history를 기반으로 작동하니 테스트 데이터가 불규칙적으로 변하면 결과가 좀 더 달라질 듯 합니다. 하지만 메인 컴파일러는 MSVC 이니 테스트 부탁드립니다.

zip 파일로 소스를 첨부합니다.
[test.c.zip](https://github.com/CppKorea/DesignPatternStudy/files/405491/test.c.zip)

좌표계산은 상당히 자주 사용되니 고려해도 좋을 듯 합니다.

물론 좌/우 변이 복잡한 코드나 좌변이 간단하고 우변이 복잡한 코드는 && 이 더 좋습니다.

**Comment by ArtBlnd** [comment]
```
    15:     if( (a == b) && ( c == d) )
8B 45 FC             mov         eax,dword ptr [a]  ; EAX에 A를 옾김
3B 45 F8             cmp         eax,dword ptr [b]  ; EAX 와 B를 비교함.
75 11                jne         main+5Ah (0120109Ah)  ; 같지 않을때에는 분기점프
8B 45 F4             mov         eax,dword ptr [c]  ; EAX에 C를 옾김.
3B 45 F0             cmp         eax,dword ptr [d]  ; EAX와 D를 비교함.
75 09                jne         main+5Ah (0120109Ah)  ; 분기점프
```

하지만 만약에 좌변 피연산자가 false일때에는 &보다 &&이 효율이 훨씬 좋습니다.
제 생각에는 그대로 &&을 유지해야된다고 생각이 드네요.

이 코드들 특성상 비교문 자체가 불규칙하니까 사실상 의미가 없다고 봐도 되고요.
슈퍼스칼라 처리가 된다고 한들 실질적인 CPU 사용량이 줄어드는것도 아니니까요.

만약에 둘다 true임을 비교하는 로직이 많다면 &으로 바꾸는것도 고려해볼만하겠네요.
자자 찬호님 열심히 VS키고 프로파일링합시다 ^^..

**Comment by utilForever** [comment]
Short-Circuit Evaluation 때문 'ㅁ'!

**Comment by ArtBlnd** [comment]
저... 수학여행인데....

**Comment by utilForever** [comment]
수학여행이면 노세요! 이런거 보지 말고 ㅋㅋㅋㅋ

**Comment by ArtBlnd** [comment]
사실 여러가지 사정이 있어서...

**Comment by drasley** [comment]
operator==의 경우는 false인 경우가 절반 이상일텐데 당연히 &&을 써야죠.

**Comment by ArtBlnd** [comment]
@drasley 

제 생각에는 만약에 바꾼다고 한다면 충분한 프로파일링을 통해 분석한 후 바꾸는게 옳다고 생각합니다.

**Comment by 0xWOF** [comment]
명령어 개수로 보면 그렇지만 슈퍼스칼라 기술을 고려해보면

&& 의 경우
cmp
jne
cmp
jne

의 명령레인이 종속 트리가 

cmp -> jne -> cmp -> jne 가 되어서

Thread 1
cmp
jne
cmp
jne

의 방식으로 수행되어서 true 인 경우 명령어 2개 false 인 경우 명령어 4개를 수행하게 됩니다.

& 의 경우
cmp
cmp
and

의 명령어 레인이 종속 트리가
cmp - and
cmp - 
(cmp 2개는 종속이지 않고 and 는 연산을 위해 cmp 2개의 결과가 필요)

이렇게 되어

Thread 1
cmp
and

Thread 2
cmp

의 방식으로 수행됩니다. 즉 명령어 개수는 3개로 일관되어서. true 에 밀리지만 슈퍼스칼라에 의해 클록수에서 이득을 보게 됩니다.

(여기서 나오는 Thread 는 CPU 하드웨어 단의 SMT Thread or Core입니다.)
(1 Core 내부의 복수개의 ALU, FPU 를 이용하여 구현)

현대의 대부분의 CPU가 슈퍼스칼라를 사용하고 SMT 기술(2Core 4Thread 같은)이 적용되어 있어서 테스트 해볼 가치는 있을 듯 합니다.

슈퍼스칼라 예시
<img width="369" alt="2016-09-07 11 32 19" src="https://cloud.githubusercontent.com/assets/7144012/18297834/c32bbefc-74ee-11e6-8c15-bfe002ff7df8.png">

**Comment by ArtBlnd** [comment]
클럭수를 비교해봐도 좌변 피연산자가 false일때 &보다 연산이 줄어드는건 달라짐이 없습니다.
if statement-optimize인 Short-Circuit Evaluation을 찾아보시기 바랍니다.

그렇다면 true일 경우에는 효율이 좋아지지 않느냐. 인데.
코드의 특성상 좌변이 false일 가능성이 상당히 높거나 불규칙적이며.
상황에따라 값이 심하게 변할 가능성이 있으므로
만약에 &로 변경하려면 상당한 프로파일링과 == operator를 사용하는 부분을
충분히 최적화해야합니다.

**Comment by 0xWOF** [comment]
조언 감사합니다.
하지만 Short-Circuit Evaluation 에 대해서는 저도 인지한 상태입니다.

Clock 수에서 비교를 언급한 이유는

&&
true
Clock 1 / cmp
Clock 2 / jne
Clock 3 / cmp
Clock 4 / jne

false
Clock 1 / cmp
Clock 2 / jne

&
true, false
Clock 1 / cmp, cmp
Clock 2/ and

여서 말씀드린겁니다.
CPU는 1 clock 에 복수개의 명령어를 처리합니다. (데이터 종속성만 없다면...)

최적화의 목표는 연산량보다는 연산시간인 Clock 수를 보는것이 옳다고 생각합니다.
clock 당 명령어 개수가 줄어도 남은 ALU, FPU에는 빈공백이 들어가는것이니..

**Comment by utilForever** [comment]
논의가 좀 더 필요한 부분이라 생각해서 Deferred로 변경합니다.

**Comment by ArtBlnd** [comment]
체크해본결과 아직 이 비교 오퍼레이터를 사용하는 부분이 없는지라 프로파일링이 불가능하군요.
차후에 그런 부분이 생긴다면 프로파일링 후에 다시 글 적어보도록 할게요.

**Comment by utilForever** [comment]
네, 감사합니다. 일단 이슈는 닫도록 하겠습니다.
