### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [MineScroll/Cubby#10]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/MineScroll/Cubby/blob/b1da754a3830485ae4e09e74aa82c314e768a4b6/Sources/main.cpp#L15)" does not contain [corresponding try and catch instructions](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main) so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706)?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108) like they are described by Danny Kalev?

**Comment by utilForever** [comment]
Thanks, I'll consider your suggestion. (in milestone v0.12)

**Comment by utilForever** [comment]
As you can see, it doesn't really help the debugger. If the exception is not caught, it will show you the exact location in source, where the exception is shown. So, this only makes sense in release build. I will add its code that is executed in release build only.

**Comment by elfring** [comment]
Would you like to [reconsider consequences from implementation-defined behaviour](https://stackoverflow.com/questions/5557555/raii-and-stack-unwinding)?

**Comment by utilForever** [comment]
Yes, I consider [aschepler's answer](http://stackoverflow.com/a/5569878).
- Avoid std::abort.
- Either avoid std::exit or avoid all objects with static storage duration.
- Put a catch (...) handler in main, and make sure no allocations or exceptions happen in or after it.
- Avoid the other programming errors that can cause std::terminate.
  - (On some implementations, functions compiled with a C compiler act like they have C++'s empty throw() specification, meaning that exceptions cannot be thrown "past" them even though they have no destructors to be called.)

**Comment by utilForever** [comment]
Maybe, I guess...

```
int main()
{
#ifndef _DEBUG
    try
    {
#endif
        ...
#ifndef _DEBUG
    }
    catch (...)
    {
        ...
    }
#endif
}
```
