### ISSUE TITLE
화로 사용시 렌더링 깨짐

### ISSUE THREAD

**Issue by ghost** [MineScroll/Cubby#11]
<img width="576" alt="cubby-crash" src="https://cloud.githubusercontent.com/assets/17694801/18370724/3d203da6-766a-11e6-8943-8ae109526e6d.PNG">
<img width="794" alt="cubby-log" src="https://cloud.githubusercontent.com/assets/17694801/18370711/22d09496-766a-11e6-8a97-6b26a5722350.PNG">
별건 아닌데.. 시험 삼아 실행해 보는 중에 발견해서 올려봅니다.

**Comment by utilForever** [comment]
Could you play again? I think that it is resolved.

**Comment by utilForever** [comment]
Fixed in 10df27d.
