### ISSUE TITLE
팅김버그

### ISSUE THREAD

**Issue by mimicryluden** [MineScroll/Cubby#13]
제가 엄청난 테스트(30번)끝에 알아냈습니다.
보물 상자를 열면 팅기는 버그라고 생각했는데 엄청 자세히 가서 열지 않아도 게임이 꺼지고 위에 올라타도 게임이 꺼지길래 뭐지... 하고 계속 테스트를 했더니 팅기기직전 매의 눈으로 위에 뜬 미믹이라는 HP바를 보았습니다. 그 후 저는 보물상자에 계속 활을 쏘았고 보물상자 중에 공격이 가능한 보물상자가 있었고 이러한 보물상자를 조금만 건들기라도 하면 엔진이 꺼지는 것을 알아냈습니다.

결론:미믹 때문에 계속 꺼짐

**Comment by utilForever** [comment]
제보 고맙습니다. 확인해 보겠습니다.

**Comment by utilForever** [comment]
dafce04 에서 고쳤습니다. 이슈 닫습니다.
