### ISSUE TITLE
m_Color (Chunk::GetActive 456 line) 잘못된 메모리 주소 참조 오류

### ISSUE THREAD

**Issue by DevSDK** [MineScroll/Cubby#15]
청크를 로드할때 해당 맴버에 잘못된 메모리 주소가 넘어갔었습니다.
Breaking Point 걸어서 재 확인했을땐 문제가 없었고
아마도 청크가 다 로드 되기전 다음청크로 넘어가려고 했을때 발생했던것 같네요.
[![Cap 2016-09-28 09-34-28-327.png](https://s12.postimg.org/6bzgzpse5/Cap_2016_09_28_09_34_28_327.png)](https://postimg.org/image/np9reknp5/)

**Comment by utilForever** [comment]
제보 고맙습니다. 확인해 보겠습니다.

**Comment by utilForever** [comment]
간헐적으로 발생하는 문제로 보입니다. 지속적인 추적이 필요해 보이네요.
혹시 정확한 스텝을 발견하게 된다면, 알려주시기 바랍니다.
