### ISSUE TITLE
NVIDIA Optimus 미지원

### ISSUE THREAD

**Issue by ghost** [MineScroll/Cubby#16]
Nvidia Optimus 기술이 적용된 노트북에서 외장 그래픽 카드가 아닌 내장 그래픽 카드로 동작하는 듯 합니다.
`extern "C" {_declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;}` 코드를 전역 범위에 추가하면 해결할 수 있을 듯 합니다.

참고:
- http://pastebin.com/QHRfcvhM
- http://pastebin.com/udCPkEzp
- [Nvidia Optimus Programming Guide](http://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf)

**Comment by Revimal** [comment]
멀티플랫폼 지원을 위해서 Preprocessor Macro를 통해서 각 운영체제별로 다르게 설정해주어야 할 듯 합니다.
만일 Optimus와 같은 내-외장 그래픽 전환간에 문제가 있다면 AMD Enduro 칩셋에 대한 지원 또한 고려를 해봐야 되고요.
따라서, 본인은 다음과 같은 소스를 제안합니다. 문제점이 있다면 말씀주세요.

```
#if defined(WIN32)
    extern "C" { __declspec(dllexport) DWORD NvOptimusEnablement=0x00000001; } 
    extern "C" { __declspec(dllexport) DWORD AmdPowerXpressRequestHighPerformance = 0x00000001;}
#else 
    extern "C" { int NvOptimusEnablement = 1; }
    extern "C" { int AmdPowerXpressRequestHighPerformance = 1;}
#endif
```

Reference:
http://developer.amd.com/community/blog/2015/10/02/amd-enduro-system-for-developers/

**Comment by utilForever** [comment]
제안 고마워, 코드 반영할게.

**Comment by utilForever** [comment]
5b31b75 에서 고쳤습니다.
