### ISSUE TITLE
Uninitialized 'counter' variable used if file isn't properly opened.

### ISSUE THREAD

**Issue by ghost** [MineScroll/Cubby#17]
In function `void CreateCharacter::UpdateCustomCounter(int incrementValue)`, uninitialized 'counter' variable is in use.

If `file.is_open()` returns `false`, `counter` will be uninitialized, which is used in `sprintf` function.

**Comment by utilForever** [comment]
Thanks. I'll check it.

**Comment by utilForever** [comment]
Fixed in 0629c0f.
