### ISSUE TITLE
모루와 화로가 맵 범위에서 나갔다가 들어오면 사라집니다

### ISSUE THREAD

**Issue by Hamule** [MineScroll/Cubby#19]
제곧내 
아마 플레이어 주위 일정범위만 맵이 나오는데, 그 범위 넘어서 다시 돌아오면 사라집니당/

**Comment by utilForever** [comment]
제보 감사합니다. 한 번 확인해 보겠습니다.

**Comment by utilForever** [comment]
Declined - Coming soon...
