### ISSUE TITLE
Execute problem..

### ISSUE THREAD

**Issue by rinechran** [MineScroll/Cubby#2]
i down zipfile and it is Extracting

so i excute Cubby.exe progream 

but error...  print..

C:\Users\rinechran>C:\Users\rinechran\Downloads\Cubby-master\Cubby-master\Cubby.exe
Can't load '../Resources/config/settings.ini'
Can't load '../Resources/config/options.ini'

i Search them file, It confirmed that in this file.

**Comment by utilForever** [comment]
Thanks. I'll check it.

**Comment by utilForever** [comment]
I fixed source files path and resource files path. Check that problem is resolved.

**Comment by rinechran** [comment]
thank you
