### ISSUE TITLE
특정 디스플레이 상황에서 CubbyWindow 생성 불가능

### ISSUE THREAD

**Issue by Astoration** [MineScroll/Cubby#23]
특정 디스플레이 상황에서 CubbyWindow가 생성되지 않는 이슈가 있는듯 합니다
대표적으로 RDP를 사용중일때나 연결된 메인 디스플레이를 비활성화하고 다른 디스플레이를 사용하고 있을때 등에 Window를 만들지 못하고 종료됩니다.

```
m_pWindow = glfwCreateWindow(m_windowWidth, m_windowHeight, "Cubby", nullptr, nullptr);
if (!m_pWindow)
{
    glfwTerminate();
    exit(EXIT_FAILURE);
}
```

부분에서 세번째 인자인 모니터 부분에 대한 처리가 필요해보입니다

**Comment by utilForever** [comment]
제보 감사합니다. 한 번 확인해 보겠습니다.

**Comment by utilForever** [comment]
Declined - Coming soon...
