### ISSUE TITLE
보물을 찾을시 게임팅김...

### ISSUE THREAD

**Issue by rinechran** [MineScroll/Cubby#3]
보물을 찾을시 게임팅김...

**Comment by utilForever** [comment]
He said "If player found treasure, the client is crashed.".
I'll check it.

**Comment by rinechran** [comment]
thank you

**Comment by utilForever** [comment]
I can open treasure as below. Could you check it again?
![image](https://cloud.githubusercontent.com/assets/5622661/18319328/32a5ae66-7560-11e6-8813-429c54a69a9b.png)

**Comment by ArtBlnd** [comment]
덤프나 콜스택을 꼭 올려주세요.

**Comment by rinechran** [comment]
<img width="720" alt="default" src="https://cloud.githubusercontent.com/assets/15512801/18376499/b3469ffe-769a-11e6-9b0e-c0b9b2f5cafb.PNG">

When I going another treasure , it is crash

**Comment by rinechran** [comment]
i will upload a big dump and Call stack, , go home.

**Comment by utilForever** [comment]
Could you play again? I think that it is resolved.

**Comment by utilForever** [comment]
Fixed in 10df27d.
