### ISSUE TITLE
Farming System

### ISSUE THREAD

**Issue by utilForever** [MineScroll/Cubby#32]
Declined - Coming soon...

**Comment by ghost** [comment]
본 기능은 https://github.com/JunHo-Seo/Cubby/tree/Agriculture 에서 작업 중입니다.

현재까지 작업한 사항은 
1. 경작 시스템 (호미로 밭가는 거..) 추가
2. 씨앗 아이템 추가
3. 싹, 밀 블럭 추가
4. 블럭 설치 기능 추가 (제한적으로. 특히 Dirt같이 ColorMatching이 안되는 블럭은 제외되어있음)
입니다. 농사는 구체적으로 기획이 나온게 없어서.. 일단 임의로 개발하고 있습니다.

현재 알려진 문제점은
1. 전용 그래픽, 애니메이션 부재 (호미는 곡괭이 것을, 씨앗은 금을, 싹, 밀 블럭은 그냥 색깔 놀음 중)
2. 인벤토리에서 호미와 곡괭이가 겹침
3. ColorMatching이 되지 않는 블럭을 설치할 수 없음
4. 씨앗을 사용해도 수가 줄지 않음
5. 인게임 시간 측정 시스템 부재 (즉, 성장 측정이 불가능)
6. 기존 시스템에 덧붙여 만든 것이라 관리가 어려움. (ex: 호미는 곡괭이를 참고해서 만듬, Bud, Wheat은 Block으로 처리되고 있음)
등이 있습니다.

앞으로 작업할 내용은
1. 호미와 곡괭이가 겹치는 치명적인 버그 수정
2. 씨앗이 Consumable하게 만들기
3. 비료 아이템 추가 (성장 테스트용)
4. 농사 시스템따로 분리
5. ColorMatching 문제 해결
6. 게임 내 시간 측정 시스템 작업
7. 야생 벼 추가 <- 이건 나무 설치하듯 하면 될 것 같다고 생각 중입니다.
등이 있습니다.

... 너무 오래 작업을 쉬어서 생존 보고겸 올립니다. 여기에 쓰는게 적절할 진 모르겠지만..
