### ISSUE TITLE
맵 일부 구간 캐릭터 안보임.

### ISSUE THREAD

**Issue by rinechran** [MineScroll/Cubby#4]
<img width="564" alt="1" src="https://cloud.githubusercontent.com/assets/15512801/18281331/73a66d66-7497-11e6-9e1f-74c700723233.PNG">

**Comment by rinechran** [comment]
<img width="589" alt="2" src="https://cloud.githubusercontent.com/assets/15512801/18281347/887ecbb6-7497-11e6-8e05-99090fe0a0aa.PNG">

정확한 위치는 모르겠습니다.

**Comment by utilForever** [comment]
He said "The character isn't visible in the part of map".
I'll check it.

**Comment by rinechran** [comment]
thank you for the  trenaslate

**Comment by utilForever** [comment]
Thanks. Fixed in 10df27d
