### ISSUE TITLE
Error occurs when my character has been attacked by monsters

### ISSUE THREAD

**Issue by SeolYang** [MineScroll/Cubby#5]
![desktop 2016 09 07 - 10 07 28 03 mp4_20160907_101444 101](https://cloud.githubusercontent.com/assets/9394823/18296341/f24822da-74e3-11e6-90bb-a5255adbce15.jpg)

**Comment by utilForever** [comment]
Thanks. I'll check it.

**Comment by ArtBlnd** [comment]
호출스택을 전부 주시면 도움이 될것같네요.

**Comment by SeolYang** [comment]
Here is full version of callstack :)
![fullofcallstack](https://cloud.githubusercontent.com/assets/9394823/18296571/82d21aa8-74e5-11e6-8646-4a9891146a68.PNG)

**Comment by utilForever** [comment]
Could you play again? I think that it is resolved.

**Comment by utilForever** [comment]
Fixed in 10df27d.
