### ISSUE TITLE
for 문을 사용할때 size_t를 사용하네요.

### ISSUE THREAD

**Issue by ArtBlnd** [MineScroll/Cubby#6]
![104](https://cloud.githubusercontent.com/assets/2209400/18296661/20ffc374-74e6-11e6-9bdb-6156eb297f78.png)

size_t를 사용하는 이유를 모르겠어요. 따로 사용하는 이유가 있으신가요?
size_t같은경우에는 메모리에 관련된 Offset 등등을 정의할때 사용하는데.
size의 크기. 즉 int 로 정의되어있는 부분에 size_t를 사용하는 이유를 사실 잘 모르겠네요...

**Comment by utilForever** [comment]
`<vector>`에서 `size()` 메서드의 리턴 타입은 `size_type`인데, 뜯어보면 `size_t`이고, 다시 뜯으면 `unsigned int`입니다. 사실 뭐를 써도 마찬가지겠네요. (...)

**Comment by ArtBlnd** [comment]
64비트에서의 size_t는 unsigned long long입니다. 32비트일때의 값과 다르지 않나요? warning을 출력하네요.

**Comment by utilForever** [comment]
`size_t`를 `int`로 변환하면서 warning이 발생하네요. warning level 4로 바꿔서 고쳐야하는데, 아직 작업 시작을 하지 않은 상태입니다. 고칠 때 참고하겠습니다. 감사합니다.

**Comment by utilForever** [comment]
size_t는 사용하되, size_t를 int로 변환하는 문제를 수정할 예정입니다.
size_t를 사용하는 곳에서 받는 데이터의 타입도 size_t로 변경하는 작업을 시작합니다.

**Comment by ArtBlnd** [comment]
이 경우에는 size_t로 정의된 for 문에서 64Bit 레지스터로 작업하고 메모리에 참조할때 32Bit 레지스터로 강제 캐스팅된 오프셋을 사용하므로 문제가 될수 있다고 생각합니다. 추가적인 오버헤드가 발생된다고 볼수도 있겠네요 (이대로 컴파일 된다면.) auto로 수정해도 괜찮을것같고 타입에 따라 uint32_t (unsigned int)로 바꿔주는것도 괜찮을것같네요.

**Comment by utilForever** [comment]
Range-based for도 고려해 보겠습니다.
다만, 지금 머리가 너무 아프고 어지러워서 밤늦게 작업하던지 할게요. @_@;

**Comment by utilForever** [comment]
작업하다가 많이 꼬여버려서 전부 롤백했습니다.
정적 분석하면서 Warning Level 4에서 나오는 경고들 위주로 수정할게요.

**Comment by ArtBlnd** [comment]
#24 부분에서 대부분 수정했습니다. size_t로 통합했습니다.
