### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [MineScroll/Cubby#9]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr)"?

Update candidates:
- [CheckBox](https://github.com/MineScroll/Cubby/blob/57b75b9ad3ee0c7850f9201127027105d1a7c854/Sources/GUI/Checkbox.cpp#L63)
- [CraftingGUI](https://github.com/MineScroll/Cubby/blob/519c3bf723dd6a6a3fcba562539c5179892ddafa/Sources/GameGUI/CraftingGUI.cpp#L20)
- [QuitPopup](https://github.com/MineScroll/Cubby/blob/519c3bf723dd6a6a3fcba562539c5179892ddafa/Sources/Frontend/Pages/QuitPopup.cpp#L20)

**Comment by utilForever** [comment]
Thanks. I'll take refactoring after check it is safe and efficient.

**Comment by utilForever** [comment]
I think that your "update candidates" are suitable for "[std::shared_ptr](http://en.cppreference.com/w/cpp/memory/shared_ptr)" (pRenderer is used for many classes). However, I don't know how efficient it is. Let's end here for now. If you provide another issue about smart pointers, we will discuss it.
